@AspNetDemos.API_HostAddress = https://localhost:44373

### Valid request
POST {{AspNetDemos.API_HostAddress}}/v1/recipe
Accept: application/json
Content-Type: application/json
{
    "Id": "recipe-123",
    "Name": "Simple Bread"
}

### Too short Id
POST {{AspNetDemos.API_HostAddress}}/v1/recipe
Accept: application/json
Content-Type: application/json
{
    "Id": "123",
    "Name": "Simple Bread"
}

### Id is number instead of string
POST {{AspNetDemos.API_HostAddress}}/v1/recipe
Accept: application/json
Content-Type: application/json
{
    "Id": 123,
    "Name": "Simple Bread"
}

### Name too short
POST {{AspNetDemos.API_HostAddress}}/v1/recipe
Accept: application/json
Content-Type: application/json
{
    "Id": "recipe-123",
    "name": "Si"
}

### Name missing from request
POST {{AspNetDemos.API_HostAddress}}/v1/recipe
Accept: application/json
Content-Type: application/json
{
    "Id": "recipe-123"
}

### Id missing from request
POST {{AspNetDemos.API_HostAddress}}/v1/recipe
Accept: application/json
Content-Type: application/json
{
    "name": "Simple Bread"
}

### Empty request (415)
POST {{AspNetDemos.API_HostAddress}}/v1/recipe
Accept: application/json
Content-Type: application/json

### Empty request without Content-Type (415)
POST {{AspNetDemos.API_HostAddress}}/v1/recipe
Accept: application/json

### Empty JSON request
POST {{AspNetDemos.API_HostAddress}}/v1/recipe
Accept: application/json
Content-Type: application/json
{}